name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build: # You can rename this job if you like, e.g., 'test' or 'checks'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false # Keep running other matrix jobs even if one fails
      matrix:
        python-version: ["3.10", "3.11"] # Add/remove versions as needed

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip' # Enable caching for pip dependencies to speed up runs

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # This command installs the 'codeconcat' package itself
        # plus all packages listed under [project.optional-dependencies.test]
        # in your pyproject.toml file (e.g., ruff, mypy, pytest).
        pip install .[test]

    - name: Lint and Format Check with Ruff
      run: |
        # Check if code is formatted according to Ruff rules (like black)
        ruff format --check .
        # Check for code style issues, import errors, etc. (like flake8, isort)
        ruff check .

    - name: Analyse code with Mypy
      run: |
        # Ensure mypy runs on your source code and test directories
        mypy codeconcat tests # Adjust these paths if your structure differs

    - name: Run tests with Pytest
      run: |
        pytest
