name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false # Keep running other matrix jobs even if one fails
      matrix:
        python-version: ["3.10", "3.11"] # Add other versions you support

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip' # Cache pip dependencies

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Install the package itself and all dependencies defined
        # in [project.optional-dependencies.test] in pyproject.toml
        # Ensure mypy, types-setuptools, pytest (if used) are listed there.
        pip install .[test]

    - name: Lint and Format Check with Ruff
      run: |
        # Check formatting (without changing files)
        ruff format --check .
        # Check linting rules
        ruff check .

    - name: Analyse code with Mypy
      # This step will now find the 'mypy' command because it was installed
      # in the 'Install dependencies' step via the [test] extras.
      run: |
        mypy codeconcat tests # Adjust paths if your structure is different

    - name: Run tests with Pytest
      run: |
        pytest
